jdk: openjdk8
language: java
sudo: false

git:
  depth: false

services:
  - docker

install: true

branches:
  only:
  - master
  - /^v.*$/

cache:
  directories:
    - $HOME/.m2/repository

before_install:
  - sudo apt-get install -y jq

before_deploy:
  - FINAL_VERSION=$(docker run --rm -v `pwd`:/repo gittools/gitversion:latest-linux /repo /nocache | jq -r '.SemVer')
  - mvn versions:set -DnewVersion=$FINAL_VERSION
  - mvn package -Dmaven.test.skip=true

deploy:
  # Deploy releases to bintray
  - provider: bintray
    skip_cleanup: true        # required to prevent Travis from cleaning the workspace before deployment
    file: target/bintray.json # defines the Bintray project to deploy to, and what to deploy and where to.
    user: bangroot # fill in your account name
    key: $BINTRAY_API_KEY            # reference to your Bintray API key
    on: # only deploy when
      repo: sixrocketsstrong/gql-java # only for this repo
      tags: true
