jdk: openjdk8
language: java
sudo: false

git:
  depth: false

services:
  - docker

install: true

branches:
  only:
  - master
  - /^.*\.RELEASE$/

cache:
  directories:
    - $HOME/.m2/repository

before_deploy:
  - mvn versions:set -DnewVersion=`echo -e "$TRAVIS_TAG" | sed -e "s/\.RELEASE//g"`
  - mvn package -Dmaven.test.skip=true

deploy:
  # Deploy releases to bintray
  - provider: bintray
    skip_cleanup: true        # required to prevent Travis from cleaning the workspace before deployment
    file: target/bintray.json # defines the Bintray project to deploy to, and what to deploy and where to.
    user: bangroot # fill in your account name
    key: $BINTRAY_API_KEY            # reference to your Bintray API key
    on: # only deploy when
      repo: sixrocketsstrong/gql-java # only for this repo
      tags: true
